# Generated by Django 4.1.1 on 2023-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_remove_book_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
