# Generated by Django 4.1.1 on 2023-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
